#!/bin/bash

ifconfig | grep ": " | cut -d":" -f1 > /tmp/pegainterfaces.txt
ARQ=$(</tmp/pegainterfaces.txt)
export amarelo='\033[01;33m'
export null='\033[0m'

echo -e "${amarelo}[+]-----> IP's <-----[+]${null}"
echo
for inter in $ARQ; do
  IP=$(ifconfig "$inter" | egrep 'ether|inet' | grep -E '(\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}' | awk '{print $2}')
  echo -e "$inter --> ${amarelo}$IP${null}"
done
rm -rf /tmp/pegainterfaces.txt 2>/dev/null
